"""
Helpers for emitting LaTeX-consumable artefacts from the exercise pipelines.

Every ``exerciseN/main.py`` builds a ``TexWriter`` and, as it produces numerical
results, records them through :meth:`TexWriter.cmd` (scalar macros) or
:meth:`TexWriter.body` (multi-line table bodies). The writer is then saved to
``report/generated/exN.tex`` and the LaTeX report ``\input``s it.

This keeps every number visible in the PDF strictly in sync with the output
of the Python code — nothing is hardcoded in the .tex sources anymore.
"""

from __future__ import annotations

import os
from typing import Iterable


# ---------------------------------------------------------------------------
# Number formatting
# ---------------------------------------------------------------------------
def fnum(x: float, d: int = 4, math: bool = True) -> str:
    """Format ``x`` with ``d`` decimals, optionally wrapping in math delimiters.

    NaN / infinity produce a plain ``\\text{NaN}`` / ``\\infty`` token so that
    the resulting LaTeX still compiles even if an estimator fails on a tail
    replication.
    """
    try:
        fx = float(x)
    except (TypeError, ValueError):
        return r"$\text{NA}$" if math else "NA"
    if fx != fx:                                       # NaN
        return r"$\text{NaN}$" if math else "NaN"
    if fx == float("inf"):
        return r"$\infty$" if math else "inf"
    if fx == float("-inf"):
        return r"$-\infty$" if math else "-inf"
    s = f"{fx:.{d}f}"
    return f"${s}$" if math else s


def fint(x: int, math: bool = True) -> str:
    s = f"{int(x)}"
    return f"${s}$" if math else s


def fpct(x: float, d: int = 2, math: bool = False) -> str:
    """Format ``x`` as a percentage (value is already in percentage units)."""
    s = f"{x:.{d}f}\\%"
    return f"${s}$" if math else s


def fsig(x: float, d: int = 2) -> str:
    """Format ``x`` in scientific notation with ``d`` significant digits."""
    try:
        fx = float(x)
    except (TypeError, ValueError):
        return r"$\text{NA}$"
    if fx == 0.0:
        return "$0$"
    # Build the mantissa / exponent halves manually so the closing brace is
    # placed *before* the trailing $.
    s = f"{fx:.{d}e}"          # e.g. "4.88e-05"
    mant, exp = s.split("e")
    exp = int(exp)             # drops leading zeros and sign handling
    return f"${mant}\\times 10^{{{exp}}}$"


# ---------------------------------------------------------------------------
# TeX writer
# ---------------------------------------------------------------------------
class TexWriter:
    """Accumulate macros + environment blocks for one exercise."""

    def __init__(self, header: str = "") -> None:
        self._lines: list[str] = []
        if header:
            self._lines.append(f"% {header}")

    # -- scalar macros --
    def cmd(self, name: str, body: str) -> None:
        """Emit ``\newcommand{\name}{body}``.

        ``body`` is passed through untouched, so callers are responsible for
        any math-mode delimiters. Pair with :func:`fnum` etc.
        """
        self._lines.append(r"\newcommand{\%s}{%s}" % (name, body))

    # -- multi-line body macros (for tabular / centerline lists) --
    def body(self, name: str, rows: Iterable[str]) -> None:
        """Emit ``\newcommand{\name}{ <rows> }``.

        Rows are joined with newlines. Trailing ``\\\\`` should already be
        included in each row where required by the tabular caller.
        """
        self._lines.append(r"\newcommand{\%s}{%%" % name)
        for row in rows:
            self._lines.append(row)
        self._lines.append("}")

    # -- free-form text --
    def raw(self, line: str = "") -> None:
        self._lines.append(line)

    # -- save --
    def save(self, path: str) -> str:
        os.makedirs(os.path.dirname(path), exist_ok=True)
        with open(path, "w", encoding="utf-8") as f:
            f.write(
                "% AUTO-GENERATED BY PS2/<exercise>/main.py — DO NOT EDIT.\n"
                "% Re-run ``python main.py`` from the PS2 root to refresh.\n\n"
            )
            f.write("\n".join(self._lines))
            f.write("\n")
        return path


# ---------------------------------------------------------------------------
# Project paths
# ---------------------------------------------------------------------------
def generated_dir(cfg: dict) -> str:
    """Resolve ``report/generated/`` relative to the PS2 root."""
    here = os.path.dirname(os.path.abspath(__file__))
    rel = cfg.get("output", {}).get("tex_generated_dir", "report/generated")
    return os.path.abspath(os.path.join(here, rel))
